### ISSUE TITLE
size_t

### ISSUE THREAD

**Issue by ghost** [p-groarke/ns_getopt#1]
Line 363 `size_t found = -1;` doesn't really make sense.

**Comment by ghost** [comment]
Line 351 : `int parsed_raw_args = 0;`
Line 353 : `for (int i = 1; i < argc; ++i) {`
Line 363 :` int found = -1;`

Does it for me.

**Comment by alxarsenault** [comment]
Fix in pull request.

**Comment by p-groarke** [comment]
Tired ;)
