### ISSUE TITLE
GETOPT_DEBUG_MESSAGES

### ISSUE THREAD

**Issue by alxarsenault** [p-groarke/ns_getopt#3]
You are doing` #define GETOPT_DEBUG_MESSAGES 1` and then `#ifdef 
GETOPT_DEBUG_MESSAGES`.
The second one is always true since it was defined.
Use `#if GETOPT_DEBUG_MESSAGES` or `#if GETOPT_DEBUG_MESSAGES == 1` instead.

**Comment by p-groarke** [comment]
This was temporary. It'll become an option in opt::options
